name: Build LaTeX Document

on: 
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          # Debe ser el nombre exacto que aparece en tu carpeta
          root_file: texto-1.tex
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4 # SOLUCIÓN: Actualizado a v4
        with:
          name: PDF_Resultado
          path: main.pdf
