name: Build LaTeX Document

on: 
  push:
    branches:
      - main  # Asegúrate de que tu rama principal se llame main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          # IMPORTANTE: Cambia 'main.tex' por el nombre real de tu archivo
          root_file: texto-1.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF_Resultado
          path: texto-1.pdf
